Declare types for dotenv-safer
We need to declare types to fix eslint problems:
```
/home/runner/work/acre/acre/solidity/hardhat.config.ts
Error:   10:1  error  Unsafe call of an `any` typed value             @typescript-eslint/no-unsafe-call
Error:   10:8  error  Unsafe member access .config on an `any` value  @typescript-eslint/no-unsafe-member-access
```