Set fixed initialBaseFeePerGas for integration tests
We were getting error:
ProviderError: Transaction maxFeePerGas (2714371762) is too low for the next block, which has a baseFeePerGas of 7506371783

To workaround the problem we set the initialBaseFeePerGas parameter to
the default value specified in https://hardhat.org/hardhat-network/docs/reference#initialbasefeepergas