Fix Jest and @orangekit/sdk support
After we added @orangekit/sdk import Jest started to complain with:
```
Jest encountered an unexpected token

Details:

/Users/jakub/workspace/acre/acre/node_modules/.pnpm/@orangekit+sdk@1.0.0-beta.9/node_modules/@orangekit/sdk/dist/src/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from "./lib";
                                                                                  ^^^^^^

SyntaxError: Unexpected token 'export'

> 1 | import { OrangeKitSdk } from "@orangekit/sdk"
    | ^
  2 | import { JsonRpcProvider } from "ethers"
  3 | import { AcreContracts } from "./lib/contracts"
  4 | import { EthereumNetwork, getEthereumContracts } from "./lib/ethereum"

  at Runtime.createScriptFromCode (../node_modules/.pnpm/jest-runtime@29.7.0/node_modules/jest-runtime/build/index.js:1505:14)
  at Object.<anonymous> (src/acre.ts:1:1)
  at Object.<anonymous> (src/index.ts:9:1)
  at Object.<anonymous> (test/modules/tbtc/Tbtc.test.ts:7:1)
```

The `@orangekit/sdk` module exports `dist/` directory containing JS files in ESM syntax.
Jest doesn't support ESM syntax, so we have to convert these JS files to
CommonJS syntax with `ts-jest/presets/js-with-ts` preset.
We have to define `transformIgnorePatterns` property as `node_modules/`
directory is excluded from transformations by default.

We also had to add `allowJs: true` in tsconfig.json to support
transformation of JS files.

Reference:
- https://stackoverflow.com/questions/75452411/why-isnt-jest-handling-es-module-dependencies
- https://stackoverflow.com/questions/49263429/jest-gives-an-error-syntaxerror-unexpected-token-export?noredirect=1&lq=1